Engine will gracefully shutdown even before FLOGO_APP_DELAYED_STOP_IN…
project-flogo/core pull request #268
Opened 2022-07-04 12:06 UTC by milanbhagwat

…TERVAL if all running actions completed

**What kind of change does this PR introduce?** (check one with "x")
```
[] Bugfix
[x] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #

**What is the current behavior?**
While graceful engine shutdown , it waits for FLOGO_APP_DELAYED_STOP_INTERVAL configured duration irrespective whether inflight actions present or not. This results into redundant delay while app repush and scale-in as engine waits for 10sec (in TCI) even when no running actions present or actions completed in lesser duration.
Usecase: let say running actions completed in 2 sec but engine still waits for 10 sec for graceful shutdown.

**What is the new behavior?**
While graceful engine shutdown , Engine will only wait for max FLOGO_APP_DELAYED_STOP_INTERVAL duration if there any inflight actions running. Engine will shutdown as soon as all running actions completed.
Usecase: let say pending actions completed in 2 sec then engine will shutdown after 2 sec and will not wait for 10 sec as a part of graceful shutdown.

2022-07-04 12:20 UTC, vnalawad-tibco requested changes

2022-07-04 12:28 UTC, milanbhagwat commented on engine/runner/runner_tracker.go
> +func (rt RunnerTracker) AddTracker() {
done the changes

2022-07-04 12:28 UTC, milanbhagwat commented on engine/runner/runner_tracker.go
> +func (rt RunnerTracker) DoneTracker() {
done the changes

2022-07-04 12:28 UTC, milanbhagwat commented on engine/runner/runner_tracker.go
> +func (rt RunnerTracker) WaitForTrackerAllDone() {
done the changes

2022-07-04 12:28 UTC, milanbhagwat commented on engine/runner/runner_tracker.go
> +func (rt RunnerTracker) WaitForActionsCompletion(timeout time.Duration) bool {
done the changes

2022-07-05 02:59 UTC, vijaynalawade approved these changes
Looks good.

2022-07-12 14:55 UTC, mellistibco approved these changes

2022-07-18 06:17 UTC, merged